### ISSUE TITLE
F5 box can't communicate with the "outside" world

### ISSUE THREAD

**Issue by erjac77** [f5devcentral/f5-vagrant-files#1] opened 2017-02-22 18:29 UTC
I'm unable to make my F5 box reach its default gateway or any other host in the same subnet.

However, two F5 boxes can communicate with each other.

@caphrim007, do you have any idea what can be the problem?

I use Vagrant on Virtualbox with the BIGIP 11.6.0.0.0.401 Vagrant box.

Thank you.

**Comment by caphrim007** [comment] 2017-02-22 19:13
@erjac77 what happens when you try? does it timeout? does it just go into a blackhole and never respond?

**Comment by erjac77** [comment] 2017-02-22 19:20
Destination Host Unreachable

**Comment by erjac77** [comment] 2017-02-22 19:24
Self:
```
[root@bigip01:zrd DOWN:Standalone] config # ping 10.10.10.11
PING 10.10.10.11 (10.10.10.11) 56(84) bytes of data.
64 bytes from 10.10.10.11: icmp_seq=1 ttl=64 time=0.051 ms
64 bytes from 10.10.10.11: icmp_seq=2 ttl=64 time=0.062 ms
64 bytes from 10.10.10.11: icmp_seq=3 ttl=64 time=0.058 ms
^C
--- 10.10.10.11 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 0.051/0.057/0.062/0.004 ms
```
Peer:
```
[root@bigip01:zrd DOWN:Standalone] config # ping 10.10.10.12
PING 10.10.10.12 (10.10.10.12) 56(84) bytes of data.
64 bytes from 10.10.10.12: icmp_seq=1 ttl=255 time=9.68 ms
64 bytes from 10.10.10.12: icmp_seq=2 ttl=255 time=5.53 ms
64 bytes from 10.10.10.12: icmp_seq=3 ttl=255 time=6.01 ms
^C
--- 10.10.10.12 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 5.533/7.078/9.682/1.851 ms
```

Default gateway:
```
[root@bigip01:zrd DOWN:Standalone] config # ping 10.10.10.1
PING 10.10.10.1 (10.10.10.1) 56(84) bytes of data.
From 10.10.10.11 icmp_seq=2 Destination Host Unreachable
From 10.10.10.11 icmp_seq=3 Destination Host Unreachable
From 10.10.10.11 icmp_seq=4 Destination Host Unreachable
^C
--- 10.10.10.1 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2999ms
```

Server on the same subnet:
```
[root@bigip01:zrd DOWN:Standalone] config # ping 10.10.10.21
PING 10.10.10.21 (10.10.10.21) 56(84) bytes of data.
From 10.10.10.11 icmp_seq=1 Destination Host Unreachable
From 10.10.10.11 icmp_seq=2 Destination Host Unreachable
From 10.10.10.11 icmp_seq=3 Destination Host Unreachable
^C
--- 10.10.10.21 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3007ms
```

**Comment by caphrim007** [comment] 2017-02-22 19:48
@erjac77 what does your route table show?

**Comment by erjac77** [comment] 2017-02-22 21:01
```
[root@bigip01:zrd DOWN:Standalone] config # tmsh show /net route
 
----------------------------------------------------------------------------------
Net::Routes
Name                Destination         Type       NextHop               Origin
----------------------------------------------------------------------------------
fe80::/64           fe80::/64           interface  tmm0                  connected
ff02::/64           ff02::/64           interface  tmm0                  connected
fe80::%vlan4093/64  fe80::%vlan4093/64  interface  /Common/external      connected
ff02:ffd::/64       ff02:ffd::/64       interface  /Common/external      connected
fe80::%vlan4092/64  fe80::%vlan4092/64  interface  /Common/ha            connected
ff02:ffc::/64       ff02:ffc::/64       interface  /Common/ha            connected
fe80::%vlan4094/64  fe80::%vlan4094/64  interface  /Common/internal      connected
ff02:ffe::/64       ff02:ffe::/64       interface  /Common/internal      connected
fe80::/64           fe80::/64           interface  /Common/socks-tunnel  connected
fe80::/64           fe80::/64           interface  /Common/http-tunnel   connected
fe80::%vlan4095/64  fe80::%vlan4095/64  interface  tmm_bp                connected
ff02:fff::/64       ff02:fff::/64       interface  tmm_bp                connected
127.1.1.0/24        127.1.1.0/24        interface  tmm0                  connected
10.10.30.0/24       10.10.30.0/24       interface  /Common/ha            connected
10.10.20.0/24       10.10.20.0/24       interface  /Common/external      connected
10.10.10.0/24       10.10.10.0/24       interface  /Common/internal      connected
127.20.0.0/16       127.20.0.0/16       interface  tmm_bp                connected
```

**Comment by caphrim007** [comment] 2017-02-22 23:26
@erjac77 how about just `route -n` from a root shell on the device. i'm curious about the eth0 settings

**Comment by erjac77** [comment] 2017-02-22 23:31
```
[root@bigip01:zrd DOWN:Standalone] config # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
127.1.1.0       0.0.0.0         255.255.255.0   U     0      0        0 tmm0
127.3.0.0       0.0.0.0         255.255.255.0   U     0      0        0 mgmt_bp
10.10.20.0      0.0.0.0         255.255.255.0   U     0      0        0 external
10.10.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.10.0.0       0.0.0.0         255.255.255.0   U     9      0        0 eth0
10.10.30.0      0.0.0.0         255.255.255.0   U     0      0        0 ha
10.10.10.0      0.0.0.0         255.255.255.0   U     0      0        0 internal
127.7.0.0       127.1.1.254     255.255.0.0     UG    0      0        0 tmm0
0.0.0.0         10.10.0.1       0.0.0.0         UG    9      0        0 eth0
```

**Comment by caphrim007** [comment] 2017-02-22 23:55
@erjac77 huh, weird, that last entry there should be `0.0.0.0      10.0.2.2`

are you setting the default gateway yourself in your vagrantfile? or using the one that is in this repository in its vanilla form?

**Comment by erjac77** [comment] 2017-02-23 00:12
Well, I changed the IP addresses and added a third interface (1.3). Maybe I screwed something in the process... I just noticed an incomplete arp on the host.

I tried the vanilla Vagrantfile from this repo and it works as expected! Sorry to have bothered you.

If I want to change the IP addresses, is there something I should be aware of?

**Comment by caphrim007** [comment] 2017-02-23 00:25
@erjac77 yeah there's one gotcha with Vagrant that is of specific concern to BIG-IP.

When doing HA configuration in BIG-IP, there is a step called Peer Discovery and a followup step that happens after that which I'll just call Peer Cert Configuration.

The discovery part can happen on any interface, but the Cert configuration can *only* happen on eth0.

The presents a particular problem with Virtualbox and Vagrant. Vagrant, by design, captures the eth0 interface and assigns it a NAT network and usually gives it the IP address 10.0.2.15.

No matter what, even if you have a thousand VMs in your Vagrantfile, you'll see that all of their eth0 interfaces all have 10.0.2.15.

This means that you, basically, cannot use Vagrant + Virtualbox to natively set up an HA configuration of BIG-IP. Sad face.

Virtualbox has a feature called NATNetwork which does, however, allow this to work, but there is a lot of automatic behavior that you expressly lose if you want to use it because

1. Vagrant quite literally was designed to not use it
2. The setup of NATNetwork itself, quite literally, does not expose in any programmatic way, the information needed to set it up in an automated way.
3. Even if it did, BIG-IP would never support it because it requires that the Virtualbox Guest Additions be installed on the guest and to do that requires a full compiler toolchain. That's not possible to install on BIG-IP. I tried...and the effort required to pull it off is so much more than any value you would ever derive from getting it working.

So,

1. Don't touch eth0
2. You can't do HA
3. You can't mount shared folders or sync folders

Hope that help, lemme know.

**Comment by erjac77** [comment] 2017-02-23 00:37
So if I understand well, 10.0.2.15 is bound to the mgmt interface and cannot (or should not) be changed. Maybe it is where I screwed up, because I changed the mgmt IP manually in the GUI.

However, I did have successfully configure HA pair. But doing so, I probably lost the ability to communicate with the "outside" world...

Again, thanks for your help, it is very appreciated!

**Comment by caphrim007** [comment] 2017-02-23 00:46
I would be curious then if you really configured it or if you just think you configured it. BIG-IP will happily go about assigning itself the values of what it thinks is its neighbor. At some point along the configuration though, it should definitely raise an error.

Maybe you can share your Vagrantfile with me so I can see if I can repro it?

You can email me a t.rupp@f5.com. Please don't post it here

**Comment by erjac77** [comment] 2017-02-23 01:12
Sure. I will send you the Vagrantfile and bigip.conf tomorrow morning when I will be in the office (it is on another setup in our lab).

But I'm pretty sure I really configured it, because when I change something on one device, the other one goes to "changes pending".

**Comment by caphrim007** [comment] 2017-02-23 01:34
Awesome. Cant wait to see it!

**Closed as completed** 2017-02-24 19:02 UTC
